Background@SETTINGS_PANEL:
	Logic: SettingsLogic
		HotkeyGroups:
			Game Commands:
				Template: TWO_COLUMN
				Types: OrderGenerator, World, Menu
			Viewport Commands:
				Template: TWO_COLUMN
				Types: Viewport
			Observer / Replay Commands:
				Template: TWO_COLUMN
				Types: Observer, Replay
			Unit Commands:
				Template: THREE_COLUMN
				Types: Unit
			Unit Stance Commands:
				Template: TWO_COLUMN
				Types: Stance
			Production Commands:
				Template: THREE_COLUMN
				Types: Production, ProductionSlot
			Support Power Commands:
				Template: THREE_COLUMN
				Types: SupportPower
			Music Commands:
				Template: TWO_COLUMN
				Types: Music
	X: (WINDOW_RIGHT - WIDTH) / 2
	Y: (WINDOW_BOTTOM -  HEIGHT) / 2
	Width: 600
	Height: 600
	Children:
		Label@SETTINGS_LABEL_TITLE:
			Y: 18
			Width: PARENT_RIGHT
			Height: 25
			Text: Settings
			Align: Center
			Font: MediumBold
			Shadow: true
		Button@RESET_BUTTON:
			X: 20
			Y: PARENT_BOTTOM - 43
			Width: 160
			Height: 29
			Text: Reset
			Font: Medium
			Shadow: true
		Button@BACK_BUTTON:
			Key: escape
			X: PARENT_RIGHT - 180
			Y: PARENT_BOTTOM - 43
			Width: 160
			Height: 29
			Text: Back
			Font: Medium
			Shadow: true
		Container@TAB_CONTAINER:
			Y: 60
			Width: PARENT_RIGHT
			Height: 25
			Children:
				Button@DISPLAY_TAB:
					X: 20
					Width: 140
					Height: 29
					Text: Display
					Font: Medium
					Shadow: true
				Button@AUDIO_TAB:
					X: 160
					Width: 140
					Height: 29
					Text: Audio
					Font: Medium
					Shadow: true
				Button@INPUT_TAB:
					X: 300
					Width: 140
					Height: 29
					Text: Input
					Font: Medium
					Shadow: true
				Button@ADVANCED_TAB:
					X: 440
					Width: 140
					Height: 29
					Text: Advanced
					Font: Medium
					Shadow: true
		Container@DISPLAY_PANEL:
			X: 15
			Y: 85
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Label@MODE_LABEL:
					X: 102
					Y: 48
					Width: 45
					Height: 25
					Align: Right
					Text: Mode:
					Font: Regular
					Shadow: true
				DropDownButton@MODE_DROPDOWN:
					X: 155
					Y: 50
					Width: 175
					Height: 25
					Font: Regular
					Text: Windowed
				Container@WINDOW_RESOLUTION:
					X: 334
					Y: 50
					Children:
						Label@At:
							Text: @
							Font: Regular
							Y: 0 - 2
							Height: 25
							Width: 25
							Align: Center
							Shadow: true
						TextField@WINDOW_WIDTH:
							X: 27
							Width: 47
							Height: 25
							MaxLength: 5
							Type: Integer
							Font: Regular
						Label@X:
							Text: x
							Font: Regular
							X: 75
							Y: 0 - 1
							Height: 25
							Width: 15
							Align: Center
							Shadow: true
						TextField@WINDOW_HEIGHT:
							X: 91
							Width: 47
							Height: 25
							MaxLength: 5
							Type: Integer
							Font: Regular
				Checkbox@HARDWARECURSORS_CHECKBOX:
					X: 105
					Y: 90
					Width: 200
					Height: 20
					Font: Regular
					Text: Use Hardware Cursors
				Label@VIDEO_DESC:
					X: 82
					Y: 116
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Left
					Text: Mode, resolution, and cursor changes will be applied after the game is restarted
					Shadow: true
				Checkbox@FRAME_LIMIT_CHECKBOX:
					X: 350
					Y: 265
					Width: 200
					Height: 20
					Font: Regular
					Text: Enable Frame Limiter
				Checkbox@PIXELDOUBLE_CHECKBOX:
					X: 350
					Y: 195
					Width: 200
					Height: 20
					Font: Regular
					Text: Enable Pixel Doubling
				Checkbox@CURSORDOUBLE_CHECKBOX:
					X: 360
					Y: 220
					Width: 200
					Height: 20
					Font: Regular
					Text: Also Double Cursor
				Label@FRAME_LIMIT_DESC_A:
					X: 380
					Y: 290
					Width: 50
					Height: 25
					Text: Limit to
				TextField@FRAME_LIMIT_TEXTFIELD:
					X: 441
					Y: 291
					Width: 35
					Height: 25
					MaxLength: 3
					Type: Integer
				Label@FRAME_LIMIT_DESC_B:
					X: 482
					Y: 290
					Height: 25
					Text: FPS
				Checkbox@PLAYER_STANCE_COLORS_CHECKBOX:
					X: 25
					Y: 240
					Width: 200
					Height: 20
					Font: Regular
					Text: Player Stance Colors
				Label@PLAYER:
					Text: Player:
					X: 15
					Y: 205
				TextField@PLAYERNAME:
					Text: Name
					X: 65
					Y: 195
					Width: 145
					Height: 25
					MaxLength: 16
				ColorPreviewManager@COLOR_MANAGER:
				DropDownButton@PLAYERCOLOR:
					X: 215
					Y: 195
					Width: 70
					Height: 25
					IgnoreChildMouseOver: true
					Children:
						ColorBlock@COLORBLOCK:
							X: 5
							Y: 6
							Width: PARENT_RIGHT - 35
							Height: PARENT_BOTTOM - 12
				Label@STATUS_BARS:
					X: 25
					Y: 325
					Text: Status Bars:
				DropDownButton@STATUS_BAR_DROPDOWN:
					X: 115
					Y: 315
					Width: 170
					Height: 25
					Font: Regular
					Text: Standard
				Checkbox@DISPLAY_TARGET_LINES_CHECKBOX:
					X: 25
					Y: 275
					Width: 200
					Height: 20
					Font: Regular
					Text: Display Target Lines
				Label@LOCALIZATION_TITLE:
					Y: 370
					Width: PARENT_RIGHT
					Font: Bold
					Text: Localization
					Align: Center
					Visible: false
				Label@LANGUAGE_LABEL:
					X: 230 - WIDTH - 5
					Y: 388
					Width: 75
					Height: 25
					Align: Right
					Text: Language:
					Visible: false
				DropDownButton@LANGUAGE_DROPDOWNBUTTON:
					X: 230
					Y: 390
					Width: 200
					Height: 25
				Label@LANGUAGE_DESC_A:
					Y: 410
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: Language changes will be applied after the game is restarted
					Visible: false
				Label@LANGUAGE_DESC_B:
					Y: 435
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: Translations apply to text strings only; Speech and build icons will remain in English
					Visible: false
		Container@AUDIO_PANEL:
			X: 5
			Y: 85
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Label@SOUND_LABEL:
					X: PARENT_RIGHT - WIDTH - 285
					Y: 48
					Width: 95
					Height: 25
					Align: Right
					Text: Sound Volume:
				Slider@SOUND_VOLUME:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 54
					Width: 250
					Height: 20
					Ticks: 5
				Checkbox@CASH_TICKS:
					X: 25
					Y: 48
					Width: 200
					Height: 20
					Font: Regular
					Text: Cash Ticks
				Checkbox@MUTE_SOUND:
					X: 25
					Y: 78
					Width: 200
					Height: 20
					Font: Regular
					Text: Mute Sound
				Label@MUSIC_LABEL:
					X: PARENT_RIGHT - WIDTH - 285
					Y: 75
					Width: 95
					Height: 25
					Align: Right
					Text: Music Volume:
				Slider@MUSIC_VOLUME:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 81
					Width: 250
					Height: 20
					Ticks: 5
				Label@VIDEO_LABEL:
					X: PARENT_RIGHT - WIDTH - 285
					Y: 105
					Width: 95
					Height: 25
					Align: Right
					Text: Video Volume:
				Slider@VIDEO_VOLUME:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 111
					Width: 250
					Height: 20
					Ticks: 5
				Label@AUDIO_DEVICE_LABEL:
					X: 190 - WIDTH - 5
					Y: 184
					Width: 75
					Height: 25
					Align: Right
					Text: Audio Device:
					Shadow: true
				DropDownButton@AUDIO_DEVICE:
					X: 190
					Y: 185
					Width: 300
					Height: 25
				Label@AUDIO_DEVICE_DESC:
					Y: 207
					Width: PARENT_RIGHT
					Height: 25
					Font: Tiny
					Align: Center
					Text: Device changes will be applied after the game is restarted
					Shadow: true
		Container@INPUT_PANEL:
			X: 5
			Y: 85
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Checkbox@CLASSICORDERS_CHECKBOX:
					X: 25
					Y: 48
					Width: 250
					Height: 20
					Font: Regular
					Text: Left-click Orders
					Shadow: true
				Label@MIDDLE_MOUSE_SCROLL_LABEL:
					X: PARENT_RIGHT - WIDTH - 130
					Y: 47
					Width: 160
					Height: 20
					Font: Regular
					Text: Middle-mouse Scrolling:
					Align: Right
				DropDownButton@MIDDLE_MOUSE_SCROLL:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 46
					Width: 100
					Height: 25
					Font: Regular
				Label@MIDDLE_MOUSE_SCROLL_LABEL:
					X: PARENT_RIGHT - WIDTH - 130
					Y: 77
					Width: 160
					Height: 20
					Font: Regular
					Text: Right-mouse Scrolling:
					Align: Right
				DropDownButton@RIGHT_MOUSE_SCROLL:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 76
					Width: 100
					Height: 25
					Font: Regular
				Label@ZOOM_MODIFIER_LABEL:
					X: PARENT_RIGHT - WIDTH - 130
					Y: 106
					Width: 160
					Height: 20
					Font: Regular
					Text: Scroll-zoom Modifier:
					Align: Right
				DropDownButton@ZOOM_MODIFIER:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 106
					Width: 100
					Height: 25
					Font: Regular
					Text: Alt
				Checkbox@EDGESCROLL_CHECKBOX:
					X: 25
					Y: 78
					Width: 130
					Height: 20
					Font: Regular
					Text: Edge Scrolling
				Checkbox@ALLOW_ZOOM_CHECKBOX:
					X: 25
					Y: 108
					Width: 130
					Height: 20
					Font: Regular
					Text: Scroll Zooming
				Checkbox@LOCKMOUSE_CHECKBOX:
					X: 25
					Y: 138
					Width: 130
					Height: 20
					Font: Regular
					Text: Lock mouse to window
				Label@SCROLL_SPEED_LABEL:
					X: PARENT_RIGHT - WIDTH - 130
					Y: 135
					Width: 95
					Height: 25
					Text: Scroll Speed:
					Align: Right
				Slider@SCROLLSPEED_SLIDER:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 141
					Width: 100
					Height: 20
					Ticks: 5
					MinimumValue: 10
					MaximumValue: 50
				Label@UI_SCROLL_SPEED_LABEL:
					X: PARENT_RIGHT - WIDTH - 130
					Y: 164
					Width: 95
					Height: 25
					Text: UI Scroll:
					Align: Right
				Slider@UI_SCROLLSPEED_SLIDER:
					X: PARENT_RIGHT - WIDTH - 25
					Y: 170
					Width: 100
					Height: 20
					Ticks: 5
					MinimumValue: 1
					MaximumValue: 100
				Label@HOTKEYS_TITLE:
					Y: 200
					Width: PARENT_RIGHT
					Font: Bold
					Text: Hotkeys
					Align: Center
					Shadow: true
				ScrollPanel@HOTKEY_LIST:
					X: 15
					Y: 215
					Width: 560
					TopBottomSpacing: 4
					ItemSpacing: 4
					Height: 252
					Children:
						ScrollItem@HEADER:
							BaseName: scrollheader
							Width: 528
							Height: 13
							Visible: false
							Children:
								Label@LABEL:
									Font: TinyBold
									Width: PARENT_RIGHT
									Height: 10
									Align: Center
								ScrollItem@HEADER:
									Width: 528
									Height: 13
									Visible: false
									Children:
										Label@LABEL:
											Font: TinyBold
											Width: PARENT_RIGHT
											Height: 10
											Align: Center
								Container@TEMPLATES:
									Children:
										Container@TWO_COLUMN:
											Width: 262
											Height: 25
											Visible: false
											Children:
												Label@FUNCTION:
													Y: 0 - 1
													Width: PARENT_RIGHT - 85
													Height: 25
													Align: Right
												HotkeyEntry@HOTKEY:
													X: PARENT_RIGHT - WIDTH
													Width: 80
													Height: 25
										Container@THREE_COLUMN:
											Width: 173
											Height: 25
											Visible: false
											Children:
												Label@FUNCTION:
													Y: 0 - 1
													Width: PARENT_RIGHT - 84
													Height: 25
													Align: Right
												HotkeyEntry@HOTKEY:
													X: PARENT_RIGHT - WIDTH + 1
													Width: 80
													Height: 25
		Container@ADVANCED_PANEL:
			X: 5
			Y: 85
			Width: PARENT_RIGHT - 10
			Height: PARENT_BOTTOM
			Children:
				Checkbox@NAT_DISCOVERY:
					X: 25
					Y: 48
					Width: 200
					Height: 20
					Font: Regular
					Text: Enable Network Discovery (UPnP)
				Checkbox@PERFTEXT_CHECKBOX:
					X: 25
					Y: 78
					Width: 300
					Height: 20
					Font: Regular
					Text: Show Performance Text
				Checkbox@PERFGRAPH_CHECKBOX:
					X: 25
					Y: 108
					Width: 300
					Height: 20
					Font: Regular
					Text: Show Performance Graph
				Checkbox@FETCH_NEWS_CHECKBOX:
					X: 25
					Y: 138
					Width: 300
					Height: 20
					Font: Regular
					Text: Fetch Community News
				Checkbox@CHECK_VERSION_CHECKBOX:
					X: 25
					Y: 168
					Width: 300
					Height: 20
					Font: Regular
					Text: Check for Updates
				Checkbox@SENDSYSINFO_CHECKBOX:
					X: 25
					Y: 198
					Width: 300
					Height: 20
					Font: Regular
					Text: Send System Information
				Label@SENDSYSINFO_DESC:
					X: 25
					Y: 213
					Width: 250
					Height: 30
					Font: Tiny
					WordWrap: True
					Text: Your Operating System, OpenGL and .NET runtime versions, and language settings will be sent along with an anonymous ID to help prioritize future development.
					Shadow: true
				Label@DEBUG_TITLE:
					X: 25
					Y: 300
					Width: PARENT_RIGHT
					Font: Bold
					Text: Debug
					Shadow: true
				Checkbox@BOTDEBUG_CHECKBOX:
					X: 25
					Y: 320
					Width: 300
					Height: 20
					Font: Regular
					Text: Show Bot Debug Messages
				Checkbox@CHECKUNSYNCED_CHECKBOX:
					X: 25
					Y: 380
					Width: 300
					Height: 20
					Font: Regular
					Text: Check Sync around Unsynced Code
				Checkbox@LUADEBUG_CHECKBOX:
					X: 25
					Y: 350
					Width: 300
					Height: 20
					Font: Regular
					Text: Show Map Debug Messages
				Checkbox@REPLAY_COMMANDS_CHECKBOX:
					X: 25
					Y: 410
					Width: 300
					Height: 20
					Font: Regular
					Text: Enable Debug Commands in Replays
